FROM sphong/miniconda

COPY entrypoint.sh /usr/local/bin/entrypoint.sh

RUN conda create -y -n mpa -c conda-forge -c bioconda python=3.7.16 metaphlan=4.1.0 \
    && chmod +x /usr/local/bin/entrypoint.sh

WORKDIR /data

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
